### PR TITLE
Rewrite 1D model in Python

### PR DESCRIPTION
**Pull request by mbueti**

### CODE REVIEW

**Comment by mbueti** [comment]
[test_con_diff.pdf](https://github.com/MFJansen/1D_Overturning/files/1118144/test_con_diff.pdf)
[test_var_diff.pdf](https://github.com/MFJansen/1D_Overturning/files/1118145/test_var_diff.pdf)

**Comment by mbueti** [comment]
[test_con_diff.pdf](https://github.com/MFJansen/1D_Overturning/files/1118149/test_con_diff.pdf)
[test_var_diff.pdf](https://github.com/MFJansen/1D_Overturning/files/1118148/test_var_diff.pdf)

**Comment by mbueti** [comment]
@MFJansen alright, we have a full conversion of the constant and variable 1D models to python, with some quick pots attached! Definitely needs commenting, and then we can start thinking out the API for setting parameters and model version

**Comment by mbueti** [comment]
And a quick update to look over, there is now a model.py class, that contains all of the functionality and can be initialized in whatever number of ways we want, and a runscript that does the initialization, calls the solver, and plots the results. This should be a good first step towards modularizing the model, and makes it much more readable and testable!

**Comment by MFJansen** [comment]
Great! I will still need to look at this in somewhat more detail at some point, but from what I can see it looks nice; and it reproduces the results from the Matlab script. Thanks for taking on this task!
One thing we might want to think about in the future is if there is a better way to allow for an arbitrary profile for the diffusivity, that's not hard-coded into the model class.

**Comment by mbueti** [comment]
Thanks @MFJansen! There are a few ways we could allow the user to specify an arbitrary diffusivity profile. Two that come to mind are allowing input of raw data to fit a constant profile to as arrays of depths and diffusivity, or ingesting a passed function/lambda defined by the user, and hooking that directly into the model. Both definitely have their up and down sides, with the latter providing more precision and power, but requiring more technical expertise to utilize.

**Comment by MFJansen** [comment]
I think we should go with the second option for now (having the first one as an alternative option may be something that we could think about at some point in the future). I actually tried this briefly this morning, but didn't get it to work...

**Comment by mbueti** [comment]
I can give it a shot today. What issues did you have, just in case I run into the same roadblocks?

**Comment by MFJansen** [comment]
Never mind, I think I got it working. I will try to push a revised version later today or tomorrow. If you want to have a look over it then, I would certainly appreciate it. (There may be better ways to do this...)

**Comment by MFJansen** [comment]
I just pushed a commit with the kappa profile definition taken out of the Model class. It would be good to do the same with psi_so. Should be straightforward, but I've got some other things to do now. I'll do it when I get to it. Unless you beat me to it...

**Comment by mbueti** [comment]
Malte,

I think you'll have me beat on this one, I'm actually headed into the woods
for a weekend away as we speak. Looking forward to looking through your
changes though!

-- 
Mike Bueti

**Comment by MFJansen** [comment]
Have fun! I'll actually be out of town for the weekend as well, so we'll see...

**Pull request merged**
