### PR TITLE
Raise Exception on Outdated NumPy

### PR DESCRIPTION
**Pull request by mbueti**
@MFJansen I also made a first pass at this, I need to run some more testing, but this should get us about where we want to be

### CODE REVIEW

**Comment by MFJansen** [comment]
Given that I made changes to more or less the same effect in parallel, this would have been hard to merge. Instead, I just stole some of your ideas and incorporated them in my version. In particular, I liked the idea to have an option to compute dkappa_dz numerically in the model.
Notice, however, that this (in it's current form) only works with Numpy version 1.13 (very recent!) or later (because numpy.gradient can't handle irregular grids in earlier releases). It would be good to add a catch that checks for the Numpy version and provides a more useful error message if the numerical computation of dkappa_dz is attempted with an older version of Numpy. It wasn't immediately clear to me how to do this, so if you ca help with that I would certainly appreciate it.

**Comment by mbueti** [comment]
@MFJansen this PR has been updated, and throws an import exception for versions of numpy less than 1.13

**Review by MFJansen — COMMENTED** [review]
Thanks @mbueti !
I think we only need the check if kappa is provided as a function and dkappa_dz is not provided (in which case the code tries to compute the derivative numerically) 
Can you move the check before line 29 in model.py?

Also, it looks like you are importing numpy twice in run_column.py, and we can probably remove the commented lines 29 to 33 in run_column.py, just to keep things clean.

Also: do we need to track your .vscode/tags in GitHub?

**Comment by mbueti** [comment]
Can do! Probably a result of the merge.

And no, I think I just haven't set up my .gitignore to exclude that
workspace directory. Easily corrected!

-- 
Mike Bueti

**Pull request merged**
